package com.dphong.likescash.mock

import java.util.concurrent.atomic.AtomicLong

abstract class AbstractFakeRepository<E> {
    val autoGeneratedId: AtomicLong = AtomicLong(0)
    val data: MutableList<E> = mutableListOf()
}
