package com.dphong.likescash.mock

import java.util.concurrent.atomic.AtomicLong

abstract class AbstractFakeRepository<E> {
    protected val autoGeneratedId: AtomicLong = AtomicLong(0)
    protected val data: MutableList<E> = mutableListOf()
}
