package com.dphong.likescash.mock

import com.dphong.likescash.domain.seller.SellerDepositOrder
import com.dphong.likescash.repository.SellerDepositOrderRepository
import org.springframework.data.domain.Pageable

class FakeSellerDepositOrderRepository : SellerDepositOrderRepository, AbstractFakeRepository<SellerDepositOrder>() {
    override fun findByOrderNumber(orderNumber: String): SellerDepositOrder? =
        data.firstOrNull { it.orderNumber == orderNumber }

    override fun save(sellerDepositOrder: SellerDepositOrder): SellerDepositOrder {
        if (sellerDepositOrder.id == null || sellerDepositOrder.id == 0L) {
            val newSellerDepositOrder = SellerDepositOrder(
                autoGeneratedId.incrementAndGet(),
                sellerDepositOrder.seller,
                sellerDepositOrder.amount,
                sellerDepositOrder.orderNumber
            )
            data.add(newSellerDepositOrder)
            return newSellerDepositOrder
        } else {
            data.removeIf { it.id == sellerDepositOrder.id }
            data.add(sellerDepositOrder)
        }
        return sellerDepositOrder
    }

    override fun findAllBySellerId(sellerId: Long, pagination: Pageable): List<SellerDepositOrder> {
        return data.filter { it.seller.id == sellerId }
            .slice(IntRange(pagination.offset.toInt(), (pagination.offset + pagination.pageSize - 1).toInt()))
    }
}
