package com.dphong.likescash.mock

import com.dphong.likescash.domain.Product
import com.dphong.likescash.repository.product.ProductRepository

class FakeProductRepository : ProductRepository, AbstractFakeRepository<Product>() {
    override fun save(product: Product): Product =
        if (product.id == null || product.id == 0L) {
            val newProduct = Product(
                autoGeneratedId.incrementAndGet(),
                product.name,
                product.seller
            )
            data.add(newProduct)
            newProduct
        } else {
            data.removeIf { it.id == product.id }
            data.add(product)
            product
        }

}
