package com.dphong.likescash.mock

import com.dphong.likescash.domain.posts.Post
import com.dphong.likescash.repository.posts.PostRepository

class FakePostRepository: PostRepository, AbstractFakeRepository<Post>() {
    override fun save(post: Post): Post {
        return if (post.id == null || post.id == 0L) {
            val newPost = Post(
                id = autoGeneratedId.incrementAndGet(),
                member = post.member,
                product = post.product,
                linkUrl = post.linkUrl,
                platform = post.platform
            )
            data.add(newPost)
            newPost
        } else {
            data.removeIf { it.id == post.id }
            data.add(post)
            post
        }
    }

    override fun findAllByProductId(productId: Long): List<Post> {
        return data.filter { it.product.id == productId }
    }
}
