name: "Pull Request Labeler"
on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - id: label-the-PR
        uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
